version: "3.8"

services:
  app:
    image: node:14-alpine
    ports:
      - 8080:3000
    command: /bin/sh -c "yarn && yarn dev"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_OPTIONS: "--unhandled-rejections=throw"
      DATABASE_URL: postgresql://postgres:postgres@db/hungry_james
      LOG_LEVEL: ~
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hungry_james
